name: Build Executable .jar

on:
  push:
    branches: ["master"]
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Build Executable
      uses: gradle/gradle-build-action@v2.4.0
      with:
        arguments: desktop:dist
        
    - name: Upload Executable
      uses: actions/upload-artifact@v3.1.2
      with:
        name: piazzapanic-${{ matrix.os }}.jar
        path: ./desktop/build/libs/desktop-1.0.jar
    
