name: CI Test and Reports

on:
  push:
    branches: ["master", "ci"]
  pull_request:
    branches: ["master"]
    
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    
    permissions: 
      contents: read
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        
    - name: Run Tests with JaCoCo
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build jacocoTestReport
        
    - name: Upload JaCoCo Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: jacoco-report
        path: ./tests/build/reports/jacoco/test/html
        
    - name: Upload core Checkstyle Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: checkstyle-report-core
        path: ./core/build/reports/checkstyle
        
    - name: Upload desktop Checkstyle Report
      uses: actions/upload-artifact@v3.1.2
      with:
        name: checkstyle-report-desktop
        path: ./desktop/build/reports/checkstyle
